export const constants = {
  SEARCH_REQUEST: "REPO_SEARCH_REQUEST",
  SEARCH_SUCCESS: "REPO_SEARCH_SUCCESS",
  SEARCH_FAILURE: "REPO_SEARCH_FAILURE",

  REMOVE_REPO_ID_SUCCESS: "REMOVE_REPO_BOOKMARK_ID_SUCCESS",

  BOOKMARK_REQUEST: "REPO_BOOKMARK_REQUEST",
  BOOKMARK_SUCCESS: "REPO_BOOKMARK_SUCCESS",
  BOOKMARK_FAILURE: "REPO_BOOKMARK_FAILURE",

  CREATE_BOOKMARK_REQUEST: "CREATE_BOOKMARK_REQUEST",
  CREATE_BOOKMARK_SUCCESS: "CREATE_BOOKMARK_SUCCESS",
  CREATE_BOOKMARK_FAILURE: "CREATE_BOOKMARK_FAILURE",

  REMOVE_BOOKMARK_REQUEST: "REMOVE_BOOKMARK_REQUEST",
  REMOVE_BOOKMARK_SUCCESS: "REMOVE_BOOKMARK_SUCCESS",
  REMOVE_BOOKMARK_FAILURE: "REMOVE_BOOKMARK_FAILURE",

  GETALL_REQUEST: "BOOKMARK_REPO_GETALL_REQUEST",
  GETALL_SUCCESS: "BOOKMARK_REPO_GETALL_SUCCESS",
  GETALL_FAILURE: "BOOKMARK_REPO_GETALL_FAILURE"
};
